#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public static class CanonicalStatIdsGenerator
{
    private const string OutputPath = "Assets/Scripts/Definitions/CanonicalStatIds.cs";

    [MenuItem("Tools/Validation/Regenerate CanonicalStatIds")]
    public static void RegenerateCanonicalStatIds()
    {
        var source = GenerateSourceFromAssets();
        File.WriteAllText(OutputPath, source, new UTF8Encoding(false));
        AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
        Debug.Log($"[Validation] Regenerated '{OutputPath}' from StatDefinition assets.");
    }

    public static bool IsCanonicalStatIdsSourceCurrent(out string reason)
    {
        if (!File.Exists(OutputPath))
        {
            reason = $"{OutputPath} does not exist.";
            return false;
        }

        var expected = NormalizeLineEndings(GenerateSourceFromAssets());
        var current = NormalizeLineEndings(File.ReadAllText(OutputPath));
        if (string.Equals(expected, current, StringComparison.Ordinal))
        {
            reason = string.Empty;
            return true;
        }

        reason = $"{OutputPath} is stale. Regenerate via Tools/Validation/Regenerate CanonicalStatIds.";
        return false;
    }

    public static IReadOnlyList<string> LoadStatDefinitionIdsFromAssets()
    {
        var ids = new List<string>();
        foreach (var guid in AssetDatabase.FindAssets("t:StatDefinition", new[] { "Assets/GameData/Stats" }))
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var stat = AssetDatabase.LoadAssetAtPath<StatDefinition>(path);
            if (stat != null && !string.IsNullOrWhiteSpace(stat.Id))
                ids.Add(stat.Id);
        }

        ids.Sort(StringComparer.Ordinal);
        return ids;
    }

    private static string GenerateSourceFromAssets()
    {
        var ids = LoadStatDefinitionIdsFromAssets();
        return GenerateSource(ids);
    }

    private static string GenerateSource(IReadOnlyList<string> sortedIds)
    {
        var byDomain = new SortedDictionary<string, SortedDictionary<string, string>>(StringComparer.Ordinal);
        foreach (var id in sortedIds)
        {
            var parts = id.Split('.');
            if (parts.Length < 2)
                continue;

            var domain = parts[0];
            var constName = ToPascalIdentifier(parts.Skip(1));
            if (!byDomain.TryGetValue(domain, out var dict))
            {
                dict = new SortedDictionary<string, string>(StringComparer.Ordinal);
                byDomain[domain] = dict;
            }

            dict[constName] = id;
        }

        var sb = new StringBuilder();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated from Assets/GameData/Stats/*.asset by CanonicalStatIdsGenerator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("public static class CanonicalStatIds");
        sb.AppendLine("{");

        foreach (var (domain, values) in byDomain)
        {
            sb.AppendLine($"    public static class {ToPascalIdentifier(new[] { domain })}");
            sb.AppendLine("    {");
            foreach (var (name, id) in values)
                sb.AppendLine($"        public const string {name} = \"{id}\";");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public static IReadOnlyList<string> Catalog => _catalog;");
        sb.AppendLine();
        sb.AppendLine("    private static readonly string[] _catalog =");
        sb.AppendLine("    {");
        foreach (var id in sortedIds)
            sb.AppendLine($"        \"{id}\",");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToPascalIdentifier(IEnumerable<string> rawParts)
    {
        var sb = new StringBuilder();
        foreach (var rawPart in rawParts)
        {
            foreach (Match match in Regex.Matches(rawPart, "[A-Za-z0-9]+"))
            {
                var word = match.Value;
                sb.Append(char.ToUpperInvariant(word[0]));
                if (word.Length > 1)
                    sb.Append(word.Substring(1));
            }
        }

        if (sb.Length == 0)
            return "Value";

        if (char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.ToString();
    }

    private static string NormalizeLineEndings(string value)
    {
        return value.Replace("\r\n", "\n");
    }
}
#endif
