using System;
using UnityEngine;

[Obsolete("Legacy direct-wired transitions are deprecated. Use StateMachineDefinition transitions via UnitBrain instead.")]
[CreateAssetMenu(menuName = "RTS/FSM/Transition")]
public class BehaviourTransition : ScriptableObject
{
    public BehaviourState From;
    public string EventName;
    public BehaviourState To;

    [SerializeField, HideInInspector] private bool isAutoGenerated;
    [SerializeField, HideInInspector] private string autoGeneratedMachineId;
    [SerializeField, HideInInspector] private string autoGeneratedFromStateId;
    [SerializeField, HideInInspector] private string autoGeneratedToStateId;
    [SerializeField, HideInInspector] private string autoGeneratedConditionId;
    [SerializeField, HideInInspector] private string autoGeneratedPayload;
    [SerializeField, HideInInspector] private string autoGeneratedStableKey;
    [SerializeField, TextArea, HideInInspector] private string autoGeneratedComment;

    public bool IsAutoGenerated => isAutoGenerated;
    public string AutoGeneratedStableKey => autoGeneratedStableKey;

    public bool SetGeneratedMetadata(
        string machineId,
        string fromStateId,
        string toStateId,
        string conditionId,
        string payload,
        string stableKey,
        string comment)
    {
        var changed = false;

        changed |= SetValue(ref isAutoGenerated, true);
        changed |= SetValue(ref autoGeneratedMachineId, machineId);
        changed |= SetValue(ref autoGeneratedFromStateId, fromStateId);
        changed |= SetValue(ref autoGeneratedToStateId, toStateId);
        changed |= SetValue(ref autoGeneratedConditionId, conditionId);
        changed |= SetValue(ref autoGeneratedPayload, payload);
        changed |= SetValue(ref autoGeneratedStableKey, stableKey);
        changed |= SetValue(ref autoGeneratedComment, comment);

        return changed;
    }

    private static bool SetValue<T>(ref T field, T value)
    {
        if (Equals(field, value))
            return false;

        field = value;
        return true;
    }
}
