#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public static class StateMachineTransitionGenerator
{
    private const string MenuPath = "Tools/FSM/Generate Transition Assets from Definitions";
    private const string TransitionRootPath = "Assets/FSM/Transitions";
    private const string GeneratedLabel = "FSM-AutoGeneratedTransition";
    private const string GeneratedComment = "AUTO-GENERATED. Do not hand edit; rerun FSM transition generator.";

    private static bool generationQueued;

    static StateMachineTransitionGenerator()
    {
        QueueGenerateAll("domain reload");
    }

    [MenuItem(MenuPath)]
    public static void GenerateAllFromMenu()
    {
        GenerateAll("manual menu");
    }

    public static void QueueGenerateAll(string reason)
    {
        if (generationQueued)
            return;

        generationQueued = true;
        EditorApplication.delayCall += () =>
        {
            generationQueued = false;
            GenerateAll(reason);
        };
    }

    public static void GenerateAll(string reason)
    {
        var machineGuids = AssetDatabase.FindAssets("t:StateMachineDefinition");
        var expectedStableKeys = new HashSet<string>(StringComparer.Ordinal);
        var touchedAssets = 0;

        AssetDatabase.StartAssetEditing();

        try
        {
            foreach (var guid in machineGuids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var definition = AssetDatabase.LoadAssetAtPath<StateMachineDefinition>(path);

                if (definition == null)
                    continue;

                touchedAssets += GenerateForDefinition(definition, expectedStableKeys);
            }

            touchedAssets += DeleteStaleGeneratedTransitions(expectedStableKeys);
        }
        finally
        {
            AssetDatabase.StopAssetEditing();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        if (touchedAssets > 0)
            Debug.Log($"[FSM Transition Generator] {touchedAssets} transition asset changes ({reason}).");
    }

    private static int GenerateForDefinition(StateMachineDefinition definition, HashSet<string> expectedStableKeys)
    {
        var changed = 0;
        var machineId = string.IsNullOrWhiteSpace(definition.Id) ? definition.name : definition.Id;
        var machinePath = $"{TransitionRootPath}/{SanitizePathSegment(machineId)}";

        EnsureFolderExists(machinePath);

        foreach (var entry in definition.Transitions)
        {
            if (string.IsNullOrWhiteSpace(entry.fromStateId) || string.IsNullOrWhiteSpace(entry.toStateId))
                continue;

            var stableKey = BuildStableKey(machineId, entry);
            expectedStableKeys.Add(stableKey);

            var assetPath = BuildAssetPath(machinePath, entry.fromStateId, entry.toStateId, stableKey);
            var transition = AssetDatabase.LoadAssetAtPath<BehaviourTransition>(assetPath);

            if (transition == null)
            {
                transition = ScriptableObject.CreateInstance<BehaviourTransition>();
                AssetDatabase.CreateAsset(transition, assetPath);
                changed++;
            }

            changed += ApplyGeneratedData(transition, machineId, stableKey, entry, assetPath);
        }

        return changed;
    }

    private static int ApplyGeneratedData(
        BehaviourTransition transition,
        string machineId,
        string stableKey,
        StateTransitionEntry entry,
        string assetPath)
    {
        var wasDirty = false;

        if (!string.Equals(transition.EventName, entry.eventName, StringComparison.Ordinal))
        {
            transition.EventName = entry.eventName;
            wasDirty = true;
        }

        if (transition.SetGeneratedMetadata(machineId, entry.fromStateId, entry.toStateId, entry.conditionId, entry.conditionDescription, stableKey, GeneratedComment))
            wasDirty = true;

        var labels = new HashSet<string>(AssetDatabase.GetLabels(transition), StringComparer.Ordinal);
        if (labels.Add(GeneratedLabel))
        {
            AssetDatabase.SetLabels(transition, new List<string>(labels).ToArray());
            wasDirty = true;
        }

        if (wasDirty)
        {
            EditorUtility.SetDirty(transition);
            AssetDatabase.ImportAsset(assetPath);
            return 1;
        }

        return 0;
    }

    private static int DeleteStaleGeneratedTransitions(HashSet<string> expectedStableKeys)
    {
        var deleted = 0;
        var guids = AssetDatabase.FindAssets("t:BehaviourTransition", new[] { TransitionRootPath });

        foreach (var guid in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var transition = AssetDatabase.LoadAssetAtPath<BehaviourTransition>(path);

            if (transition == null || !transition.IsAutoGenerated)
                continue;

            if (string.IsNullOrWhiteSpace(transition.AutoGeneratedStableKey) || expectedStableKeys.Contains(transition.AutoGeneratedStableKey))
                continue;

            if (AssetDatabase.DeleteAsset(path))
                deleted++;
        }

        return deleted;
    }

    private static string BuildStableKey(string machineId, StateTransitionEntry entry)
    {
        var eventToken = NormalizeToken(entry.eventName);
        var conditionToken = NormalizeToken(entry.conditionId);
        var payloadToken = NormalizeToken(entry.conditionDescription);

        return $"machine={NormalizeToken(machineId)}|from={NormalizeToken(entry.fromStateId)}|to={NormalizeToken(entry.toStateId)}|event={eventToken}|condition={conditionToken}|payload={payloadToken}";
    }

    private static string BuildAssetPath(string machinePath, string fromStateId, string toStateId, string stableKey)
    {
        var from = SanitizePathSegment(fromStateId);
        var to = SanitizePathSegment(toStateId);
        var hash = ComputeShortHash(stableKey);

        return $"{machinePath}/{from}_to_{to}__{hash}.asset";
    }

    private static string NormalizeToken(string value)
    {
        return string.IsNullOrWhiteSpace(value) ? "_" : value.Trim();
    }

    private static string SanitizePathSegment(string value)
    {
        var normalized = NormalizeToken(value);
        var invalidChars = Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(normalized.Length);

        foreach (var ch in normalized)
        {
            if (Array.IndexOf(invalidChars, ch) >= 0 || ch == '/')
                builder.Append('_');
            else
                builder.Append(ch);
        }

        return builder.ToString();
    }

    private static string ComputeShortHash(string text)
    {
        var bytes = Encoding.UTF8.GetBytes(text);
        using var hasher = SHA256.Create();
        var hash = hasher.ComputeHash(bytes);
        return BitConverter.ToString(hash, 0, 6).Replace("-", string.Empty).ToLowerInvariant();
    }

    private static void EnsureFolderExists(string targetFolder)
    {
        var parts = targetFolder.Split('/');
        var current = parts[0];

        for (var i = 1; i < parts.Length; i++)
        {
            var next = $"{current}/{parts[i]}";
            if (!AssetDatabase.IsValidFolder(next))
                AssetDatabase.CreateFolder(current, parts[i]);

            current = next;
        }
    }
}

public sealed class StateMachineTransitionGeneratorPostprocessor : AssetPostprocessor
{
    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths)
    {
        if (!ContainsStateMachineDefinitionChange(importedAssets, deletedAssets, movedAssets, movedFromAssetPaths))
            return;

        StateMachineTransitionGenerator.QueueGenerateAll("state machine definition asset change");
    }

    private static bool ContainsStateMachineDefinitionChange(params string[][] changeSets)
    {
        foreach (var changeSet in changeSets)
        {
            if (changeSet == null)
                continue;

            foreach (var path in changeSet)
            {
                if (string.IsNullOrWhiteSpace(path) || !path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
                    continue;

                var mainType = AssetDatabase.GetMainAssetTypeAtPath(path);
                if (mainType == typeof(StateMachineDefinition))
                    return true;

                if (mainType == null && path.Contains("/Definitions/", StringComparison.Ordinal) && path.Contains("StateMachine", StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }

        return false;
    }
}
#endif
