using System.Collections.Generic;

// <auto-generated>
// This file is generated from Assets/GameData/Stats/*.asset by CanonicalStatIdsGenerator.
// Do not edit manually.
// </auto-generated>
public static class CanonicalStatIds
{
    public static class Building
    {
        public const string BuildTime = "building.buildTime";
        public const string ComfortBonus = "building.comfortBonus";
        public const string ConstructionTime = "building.constructionTime";
        public const string HitPoints = "building.hitPoints";
        public const string HousingCapacity = "building.housingCapacity";
        public const string UpgradeSlots = "building.upgradeSlots";
    }

    public static class Combat
    {
        public const string AttackRange = "combat.attackRange";
        public const string AttackSpeed = "combat.attackSpeed";
        public const string BaseDamage = "combat.baseDamage";
    }

    public static class Core
    {
        public const string MaxHealth = "core.maxHealth";
        public const string VisionRange = "core.visionRange";
    }

    public static class Item
    {
        public const string Weight = "item.weight";
    }

    public static class Movement
    {
        public const string MoveSpeed = "movement.moveSpeed";
        public const string TurnSpeed = "movement.turnSpeed";
    }

    public static class Production
    {
        public const string CarryCapacity = "production.carryCapacity";
        public const string StorageCapacity = "production.storageCapacity";
        public const string WorkSpeed = "production.workSpeed";
    }

    public static IReadOnlyList<string> Catalog => _catalog;

    private static readonly string[] _catalog =
    {
        "building.buildTime",
        "building.comfortBonus",
        "building.constructionTime",
        "building.hitPoints",
        "building.housingCapacity",
        "building.upgradeSlots",
        "combat.attackRange",
        "combat.attackSpeed",
        "combat.baseDamage",
        "core.maxHealth",
        "core.visionRange",
        "item.weight",
        "movement.moveSpeed",
        "movement.turnSpeed",
        "production.carryCapacity",
        "production.storageCapacity",
        "production.workSpeed",
    };
}
