using System.Collections.Generic;

// <auto-generated>
// This file is generated from Assets/GameData/Stats/*.asset by CanonicalStatIdsGenerator.
// Do not edit manually.
// </auto-generated>
public static class CanonicalStatIds
{
    public static class Movement
    {
        public const string MoveSpeed = "movement.moveSpeed";
        public const string Acceleration = "movement.acceleration";
        public const string TurnRate = "movement.turnRate";
        public const string TurnSpeed = "movement.turnSpeed";
    }

    public static class Combat
    {
        public const string Health = "combat.health";
        public const string HealthRegen = "combat.healthRegen";
        public const string AttackDamage = "combat.attackDamage";
        public const string BaseDamage = "combat.baseDamage";
        public const string AttackSpeed = "combat.attackSpeed";
        public const string AttackRange = "combat.attackRange";
        public const string CritChance = "combat.critChance";
        public const string CritMultiplier = "combat.critMultiplier";
        public const string Armor = "combat.armor";
        public const string MagicResist = "combat.magicResist";
        public const string BlockChance = "combat.blockChance";
        public const string DodgeChance = "combat.dodgeChance";
    }

    public static class Needs
    {
        public const string HungerRate = "needs.hungerRate";
        public const string ThirstRate = "needs.thirstRate";
        public const string FatigueRate = "needs.fatigueRate";
        public const string MoraleDecayRate = "needs.moraleDecayRate";
        public const string StressGainRate = "needs.stressGainRate";
    }

    public static class Perception
    {
        public const string PerceptionRadius = "perception.radius";
        public const string HearingRadius = "perception.hearingRadius";
        public const string VisionArc = "perception.visionArc";
        public const string MemoryDuration = "perception.memoryDuration";
    }

    public static class Production
    {
        public const string WorkSpeed = "production.workSpeed";
        public const string CarryCapacity = "production.carryCapacity";
        public const string GatherRate = "production.gatherRate";
        public const string BuildSpeed = "production.buildSpeed";
        public const string StorageCapacity = "production.storageCapacity";
    }

    public static class AI
    {
        public const string Aggression = "ai.aggression";
        public const string Courage = "ai.courage";
        public const string Obedience = "ai.obedience";
        public const string Alertness = "ai.alertness";
        public const string PerceptionRadius = "ai.perceptionRadius";
    }

    public static class Economy
    {
        public const string UpkeepRate = "economy.upkeepRate";
        public const string PopulationCost = "economy.populationCost";
    }

    public static class Lifecycle
    {
        public const string XPPerKill = "lifecycle.xpPerKill";
        public const string XPToLevel = "lifecycle.xpToLevel";
        public const string MaxLevel = "lifecycle.maxLevel";
    }

    public static class Core
    {
        public const string MaxHealth = "core.maxHealth";
        public const string VisionRange = "core.visionRange";
    }

    public static class Building
    {
        public const string Armor = "building.armor";
        public const string BuildRadius = "building.buildRadius";
        public const string BuildTime = "building.buildTime";
        public const string CaptureResistance = "building.captureResistance";
        public const string ComfortBonus = "building.comfortBonus";
        public const string ConstructionTime = "building.constructionTime";
        public const string DecayTime = "building.decayTime";
        public const string DetectionRange = "building.detectionRange";
        public const string EnergyConsumption = "building.energyConsumption";
        public const string EnergyProduction = "building.energyProduction";
        public const string Footprint = "building.footprint";
        public const string GarrisonCapacity = "building.garrisonCapacity";
        public const string HitPoints = "building.hitPoints";
        public const string HousingCapacity = "building.housingCapacity";
        public const string IsProduction = "building.is.production";
        public const string PopulationSupport = "building.populationSupport";
        public const string PowerRadius = "building.powerRadius";
        public const string ProductionSpeedMultiplier = "building.productionSpeedMultiplier";
        public const string RallyPointCount = "building.rallyPointCount";
        public const string RepairRate = "building.repairRate";
        public const string ResourceRadius = "building.resourceRadius";
        public const string ShieldPoints = "building.shieldPoints";
        public const string SightRange = "building.sightRange";
        public const string SupplyProvided = "building.supplyProvided";
        public const string SupplyUsed = "building.supplyUsed";
        public const string TrainQueueSize = "building.trainQueueSize";
        public const string TurretSlots = "building.turretSlots";
        public const string UpgradeSlots = "building.upgradeSlots";
        public const string UpgradeTimeReduction = "building.upgradeTimeReduction";
    }

    public static class Item
    {
        public const string Weight = "item.weight";
    }

    public static IReadOnlyList<string> Catalog => _catalog;

    private static readonly string[] _catalog =
    {
        Movement.MoveSpeed, Movement.Acceleration, Movement.TurnRate, Movement.TurnSpeed,
        Combat.Health, Combat.HealthRegen, Combat.AttackDamage, Combat.BaseDamage, Combat.AttackSpeed, Combat.AttackRange,
        Combat.CritChance, Combat.CritMultiplier, Combat.Armor, Combat.MagicResist, Combat.BlockChance, Combat.DodgeChance,
        Needs.HungerRate, Needs.ThirstRate, Needs.FatigueRate, Needs.MoraleDecayRate, Needs.StressGainRate,
        Perception.PerceptionRadius, Perception.HearingRadius, Perception.VisionArc, Perception.MemoryDuration,
        Production.WorkSpeed, Production.CarryCapacity, Production.GatherRate, Production.BuildSpeed, Production.StorageCapacity,
        AI.Aggression, AI.Courage, AI.Obedience, AI.Alertness, AI.PerceptionRadius,
        Economy.UpkeepRate, Economy.PopulationCost,
        Lifecycle.XPPerKill, Lifecycle.XPToLevel, Lifecycle.MaxLevel,
        Core.MaxHealth, Core.VisionRange,
        Building.Armor, Building.BuildRadius, Building.BuildTime, Building.CaptureResistance, Building.ComfortBonus,
        Building.ConstructionTime, Building.DecayTime, Building.DetectionRange, Building.EnergyConsumption,
        Building.EnergyProduction, Building.Footprint, Building.GarrisonCapacity, Building.HitPoints,
        Building.HousingCapacity, Building.IsProduction, Building.PopulationSupport, Building.PowerRadius,
        Building.ProductionSpeedMultiplier, Building.RallyPointCount, Building.RepairRate, Building.ResourceRadius,
        Building.ShieldPoints, Building.SightRange, Building.SupplyProvided, Building.SupplyUsed,
        Building.TrainQueueSize, Building.TurretSlots, Building.UpgradeSlots, Building.UpgradeTimeReduction,
        Item.Weight,
    };
}
