using System.Collections.Generic;

// <auto-generated>
// This file is generated from Assets/GameData/Stats/*.asset by CanonicalStatIdsGenerator.
// Do not edit manually.
// </auto-generated>
public static class CanonicalStatIds
{
    public static class Building
    {
        public const string Buildtime = "building.buildtime";
        public const string BuildTime = Buildtime;
        public const string Comfortbonus = "building.comfortbonus";
        public const string ComfortBonus = Comfortbonus;
        public const string Constructiontime = "building.constructiontime";
        public const string ConstructionTime = Constructiontime;
        public const string Hitpoints = "building.hitpoints";
        public const string HitPoints = Hitpoints;
        public const string Housingcapacity = "building.housingcapacity";
        public const string HousingCapacity = Housingcapacity;
        public const string IsProduction = "building.is.production";
        public const string Upgradeslots = "building.upgradeslots";
        public const string UpgradeSlots = Upgradeslots;
    }

    public static class Combat
    {
        public const string AttackRange = "combat.attackRange";
        public const string AttackSpeed = "combat.attackSpeed";
        public const string BaseDamage = "combat.baseDamage";
    }

    public static class Core
    {
        public const string MaxHealth = "core.maxHealth";
        public const string VisionRange = "core.visionRange";
    }

    public static class Item
    {
        public const string Weight = "item.weight";
    }

    public static class Movement
    {
        public const string MoveSpeed = "movement.moveSpeed";
        public const string TurnSpeed = "movement.turnSpeed";
    }

    public static class Production
    {
        public const string CarryCapacity = "production.carryCapacity";
        public const string Storagecapacity = "production.storagecapacity";
        public const string StorageCapacity = Storagecapacity;
        public const string WorkSpeed = "production.workSpeed";
    }

    public static IReadOnlyList<string> Catalog => _catalog;

    private static readonly string[] _catalog =
    {
        "building.buildtime",
        "building.comfortbonus",
        "building.constructiontime",
        "building.hitpoints",
        "building.housingcapacity",
        "building.is.production",
        "building.upgradeslots",
        "combat.attackRange",
        "combat.attackSpeed",
        "combat.baseDamage",
        "core.maxHealth",
        "core.visionRange",
        "item.weight",
        "movement.moveSpeed",
        "movement.turnSpeed",
        "production.carryCapacity",
        "production.storagecapacity",
        "production.workSpeed",
    };
}
